buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'eclipse'
    id 'idea'
    alias libs.plugins.grace.doc
    alias libs.plugins.gradle.nexus.publish
}

ext {
    isCiBuild = project.hasProperty("isCiBuild") || System.getenv().get("CI") as Boolean
    isBuildSnapshot = project.version.endsWith("-SNAPSHOT")
    isReleaseVersion = !isBuildSnapshot
}

ext."signing.keyId" = project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : System.getenv('SIGNING_KEY')
ext."signing.password" = project.hasProperty("signing.password") ? project.getProperty('signing.password') : System.getenv('SIGNING_PASSPHRASE')
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : ("${System.properties['user.home']}${File.separator}.gnupg${File.separator}secring.gpg")
ext.isReleaseVersion = !projectVersion.endsWith("SNAPSHOT")

version = project.projectVersion
group = "org.graceframework"

repositories {
    mavenCentral()
}

configurations {
    documentation
}

dependencies {
    documentation libs.javaparser
    documentation libs.groovy.core
}

def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    def buildDir = project.layout.buildDirectory
    tasks.register('clean', Delete) {
        it.delete(buildDir)
    }
}
else {
    def docsDir = project.layout.buildDirectory.dir('docs')
    cleanTask.doLast {
        ((Delete) it).delete(docsDir)
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Data Hibernate - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
}

publishGuide {
    dependsOn groovydoc
    sourceDir = project.file('src/docs')
}

tasks.register('docs') { task ->
    task.dependsOn groovydoc, publishGuide
}

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv("MAVEN_CENTRAL_USER") ?: project.hasProperty("mavenCentralUsername") ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv("MAVEN_CENTRAL_PASSWORD") ?: project.hasProperty("mavenCentralPassword") ? project.mavenCentralPassword : ''
            nexusUrl = uri("https://ossrh-staging-api.central.sonatype.com/service/local/")
            snapshotRepositoryUrl = uri("https://central.sonatype.com/repository/maven-snapshots/")
            username = mavenUser
            password = mavenPass
        }
    }
}
