buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        if (project.projectVersion.endsWith('-SNAPSHOT')) {
            maven {
                url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            }
        }
    }
    dependencies {
        classpath "io.github.gradle-nexus:publish-plugin:2.0.0"
        classpath "org.asciidoctor:asciidoctor-gradle-jvm:4.0.3"
        classpath "org.graceframework:grace-gradle-plugin:$graceVersion"
        classpath "com.github.erdi:webdriver-binaries-gradle-plugin:$webdriverBinariesVersion"
        classpath "org.gradle:test-retry-gradle-plugin:1.6.0"
    }
}

group = "org.graceframework"
version = project.projectVersion

ext {
    isTravisBuild = System.getenv().get("TRAVIS") == 'true'
    isCiBuild = project.hasProperty("isCiBuild") || System.getenv().get("CI") as Boolean
    isBuildSnapshot = version.endsWith('-SNAPSHOT')
    isReleaseVersion = !isBuildSnapshot
}

ext."signing.keyId" = System.getenv("SIGNING_KEY") ?: project.hasProperty("signing.keyId") ? project.getProperty('signing.keyId') : null
ext."signing.password" = System.getenv("SIGNING_PASSPHRASE") ?: project.hasProperty("signing.password") ? project.getProperty('signing.password') : null
ext."signing.secretKeyRingFile" = project.hasProperty("signing.secretKeyRingFile") ? project.getProperty('signing.secretKeyRingFile') : null

apply plugin: 'maven-publish'
apply plugin: "io.github.gradle-nexus.publish-plugin"

nexusPublishing {
    repositories {
        sonatype {
            def ossUser = System.getenv("SONATYPE_USERNAME") ?: project.hasProperty("sonatypeOssUsername") ? project.sonatypeOssUsername : ''
            def ossPass = System.getenv("SONATYPE_PASSWORD") ?: project.hasProperty("sonatypeOssPassword") ? project.sonatypeOssPassword : ''
            def ossStagingProfileId = System.getenv("SONATYPE_STAGING_PROFILE_ID") ?: project.hasProperty("sonatypeOssStagingProfileId") ? project.sonatypeOssStagingProfileId : ''
            nexusUrl = uri("https://s01.oss.sonatype.org/service/local/")
            snapshotRepositoryUrl = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
            username = ossUser
            password = ossPass
            stagingProfileId = ossStagingProfileId
        }
    }
}

subprojects { Project subproject ->
    ext {
        projectArtifactId = subproject.name
        isExample = subproject.name.startsWith('example')
        isPluginProject = subproject.name == 'hibernate'
    }

    if (isPluginProject) {
        group = "org.graceframework.plugins"
    }
    else {
        group = "org.graceframework"
    }
    version = project.rootProject.version

    repositories {
        mavenCentral()
        if (project.projectVersion.endsWith('-SNAPSHOT')) {
            maven {
                url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
            }
        }
    }

    if(isExample) {
        apply plugin: "groovy"

        dependencies {
            testImplementation "org.apache.groovy:groovy-test-junit5"
            testImplementation("org.spockframework:spock-core") { transitive = false}
            testImplementation "org.junit.jupiter:junit-jupiter-api"
            testImplementation "org.junit.platform:junit-platform-runner"
            testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
        }

        return
    }

    apply plugin: 'groovy'

    configurations {
        documentation.extendsFrom(compileClasspath)
    }

    if (subproject.name == 'docs') {
        return
    }

    apply plugin: 'java-library'
    apply plugin: 'maven-publish'
    apply plugin: 'checkstyle'
    apply plugin: 'codenarc'
    apply plugin: 'signing'
    apply plugin: "org.gradle.test-retry"

    if (isPluginProject) {
        apply plugin: 'org.graceframework.grace-plugin'
    }
    else {
        apply plugin: "io.spring.dependency-management"

        dependencyManagement {
            imports {
                mavenBom "org.graceframework:grace-bom:$graceVersion"
            }
            applyMavenExclusions false
            generatedPomCustomization {
                enabled = false
            }
        }
    }

    dependencies {
        documentation "org.fusesource.jansi:jansi:$jansiVersion"
        documentation "org.apache.groovy:groovy-dateutil"
        documentation "org.apache.groovy:groovy-xml"
        documentation "com.github.javaparser:javaparser-core:$javaParserCoreVersion"

        testImplementation "org.spockframework:spock-core", {
            exclude group: "org.junit.platform", module: "junit-platform-engine"
        }
        testImplementation "org.apache.groovy:groovy-test-junit5", {
            exclude group: "org.junit.platform", module: "junit-platform-launcher"
            exclude group: "org.junit.jupiter", module: "junit-jupiter-engine"
        }
        testImplementation "org.junit.jupiter:junit-jupiter-api"
        testImplementation "org.junit.platform:junit-platform-runner"
        testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
        withJavadocJar()
        withSourcesJar()
    }

    tasks.withType(Test) {
        useJUnitPlatform()
        testLogging {
            showStandardStreams = true
            exceptionFormat = 'full'
        }
        configure {
            retry {
                maxRetries = 2
                maxFailures = 20
                failOnPassedAfterRetry = true
            }
        }
    }

    groovydoc.classpath = configurations.documentation

    publishing {
        publications {
            maven(MavenPublication) {
                def projectName = subproject.name.split('-')*.capitalize().join(' ')
                artifactId = projectArtifactId

                from components.java

                versionMapping {
                    usage('java-api') {
                        fromResolutionOf('runtimeClasspath')
                    }
                    usage('java-runtime') {
                        fromResolutionResult()
                    }
                }

                afterEvaluate {
                    if(isPluginProject) {
                        artifact source:"${sourceSets.main.groovy.classesDirectory.get()}/META-INF/grails-plugin.xml",
                                classifier:"plugin",
                                extension:'xml'
                    }
                }
                pom {
                    name = projectName
                    description = "Grace Data : $projectName"
                    url = 'https://github.com/graceframework/grace-data-hibernate'

                    licenses {
                        license {
                            name = 'The Apache Software License, Version 2.0'
                            url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                            distribution = 'repo'
                        }
                    }

                    scm {
                        url = 'https://github.com/graceframework/grace-data-hibernate'
                        connection = 'https://github.com/graceframework/grace-data-hibernate'
                        developerConnection = 'https://github.com/graceframework/grace-data-hibernate'
                    }

                    developers {
                        developer {
                            id = 'rainboyan'
                            name = 'Michael Yan'
                            email = 'rain@rainboyan.com'
                        }
                    }
                }
            }
        }
    }

    afterEvaluate {
        signing {
            required = isReleaseVersion && gradle.taskGraph.hasTask("publish")
            sign publishing.publications.maven
        }
    }

    tasks.withType(Sign) {
        onlyIf { isReleaseVersion }
    }

    tasks.named('compileGroovy') {
        inputs.files(tasks.named('processResources'))
    }

    checkstyle {
        toolVersion = "10.3.2"
        configDirectory.set(rootProject.file("$rootDir/gradle/checkstyle"))
    }

    codenarc {
        toolVersion = '3.1.0'
        setConfigFile(new File("$rootDir/gradle/codenarc/codenarc.groovy"))
    }

}
