plugins {
    id 'grace.build.common'
}

dependencies {
    api libs.grace.datastore.core
    api libs.grace.datastore.gorm
    api libs.hibernate.core, {
        exclude group:'org.dom4j', module:'dom4j'
        exclude group:'jakarta.activation', module:'jakarta.activation-api'
        exclude group:'jakarta.annotation', module:'jakarta.annotation-api'
        exclude group:'jakarta.persistence', module:'jakarta.persistence-api'
    }
    api libs.hibernate.validator
    api libs.jakarta.annotation.api
    api libs.jakarta.el
    api libs.jakarta.persistence.api
    api libs.jakarta.validation
    api libs.spring.orm
    implementation libs.javassist
    implementation libs.slf4j.api

    testImplementation libs.grace.bootstrap
    testImplementation libs.grace.core
    testImplementation libs.grace.datastore.gorm.tck
    testImplementation libs.groovy.json
    testImplementation libs.groovy.sql
    testImplementation libs.jakarta.el
    testImplementation libs.jakarta.validation
    testImplementation libs.ehcache, {
        capabilities {
            requireCapability('org.ehcache:ehcache-jakarta')
        }
    }
    testImplementation libs.h2
    testImplementation libs.hibernate.jcache
    testImplementation libs.hibernate.validator
    testImplementation libs.tomcat.jdbc
    testRuntimeOnly libs.glassfish.expressly
}
