plugins {
    id 'groovy'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
}

group = 'examples'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.apache.groovy:groovy'
    implementation "org.graceframework:grace-boot:$graceVersion"
    implementation "org.graceframework:grace-core:$graceVersion"
    implementation "org.graceframework:grace-plugin-core:$graceVersion"
    implementation "org.graceframework:grace-plugin-datasource:$graceVersion"
    implementation project(":hibernate")
    implementation "org.hibernate:hibernate-ehcache:$hibernateCoreVersion"
    implementation "io.micrometer:micrometer-core:1.13.9"
    implementation "org.javassist:javassist:3.30.2-GA"

    runtimeOnly 'com.h2database:h2'

    testImplementation "org.spockframework:spock-core:$spockVersion"
    testImplementation'org.springframework.boot:spring-boot-starter-test'
}
