plugins {
    id 'groovy'
    id 'io.spring.dependency-management'
}

group = 'examples'

dependencyManagement {
    imports {
        mavenBom "org.graceframework:grace-bom:$graceVersion"
    }
}

dependencies {
    implementation project(":grace-datastore-gorm-hibernate")
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "org.slf4j:slf4j-api"
    implementation "org.graceframework:grace-core"
    testImplementation "org.spockframework:spock-core"
    testRuntimeOnly "org.slf4j:slf4j-simple"
}
