If GORM entity references some other entities, then during its constraints evaluation (validation) the constraints of the referenced entity could be 
evaluated also, if needed. There is a special parameter `cascadeValidate` in the entity mappings section, which manage the way of this _cascaded_ validation happens.

[source,groovy]
----
class Author {
    Publisher publisher

    static mapping = {
        publisher(cascadeValidate: "dirty")
    }
}

class Publisher {
    String name

    static constraints = {
        name blank: false
    }
}
----

The following table presents all options, which can be used:

[cols="1,2"]
|===
|Option |Description 

|none
|Will not do any cascade validation at all for the association.

|default
|The DEFAULT option. GORM performs cascade validation in some cases.

|dirty
|Only cascade validation if the referenced object is dirty via the `DirtyCheckable` trait. If the object doesn't implement DirtyCheckable, this will fall back to `default`.

|owned
|Only cascade validation if the entity <<gormAssociation, owns>> the referenced object. 
|===

It is possible to set the global option for the `cascadeValidate`:

[source,groovy]
.app/conf/application.groovy
----
grails.gorm.default.mapping = {
    '*'(cascadeValidate: 'dirty')
}
----
